import { Dimensions } from 'react-native'
import { Assets } from '../../assets'

export const useConstants = () => {
  const dim = Dimensions.get('screen')

  return {
    dim,
    links: {
      github: 'https://github.com/kanzitelli/rnn-starter',
      website: 'https://batyr.io',
    },
  }
}

const fontRegularName = 'SofiaPro'
export const theme = {
  font: {
    light: fontRegularName + 'Light',
    lightItalic: fontRegularName + 'Light-Italic',
    regular: fontRegularName + 'Regular',
    semibold: fontRegularName + 'SemiBold',
    semiboldItalic: fontRegularName + 'SemiBold-Italic',
    extraLight: fontRegularName + 'ExtraLight',
    extraLightItalic: fontRegularName + 'ExtraLight-Italic',
    bold: fontRegularName + 'Bold',
    boldItalic: fontRegularName + 'Bold-Italic',
    extraBold: fontRegularName + 'ExtraBold',
    extraBoldItalic: fontRegularName + 'ExtraBold-Italic',
    medium: fontRegularName + 'Medium',
    popinsSemibold: 'SofiaProSemiBold',
  },
  fontSize: {
    headingSize: 22,
    tiny: 8,
    extraVSmall: 10,
    extraSmall: 12,
    small: 14,
    medium: 15,
    regular: 16,
    large: 18,
    extraLarge: 28,
  },
  color: {
    imgBorder: '#888888',
    lightRed: '#EE313B',
    lightPink: '#F954B6',
    pink: '#EC008C',
    grey: '#A7A7A7',
    offWhite: '#F5F5F5',
    lightGrey: '#707070',
    fontBlack: '#282828',
    black: '#000000',
    flashWhite: '#EFF0F6',

    bg: '#EDF7FF',
    red: '#EE313B',
    white: '#FFFFFF',
    icnBlue: '#208DEE',
    fadeBlack: '#3E4187',
    headingBlue: '#222461',
    gray: '#979797',
    textBlue: '#3E4187',
    bgBlue: '#006DCA',
    darkBlue: '#073395',
    statusBar: '#fff',
    borderGray: '#D8E2EB',
    borderGrayLight: 'rgba(237, 247, 255, .3)',
    textPurple: '#AC4BEB',
    bgGreen: '#02C369',
    darkGreen: '#6890B2',
    purple: '#4B0081',
    skyBlue: '#3388EC',
    orange: '#E3453A',
    formBg: '#82ADD8',
  },
}

export const pageConfiguration: Configuration = {
  LOGIN: {
    title: 'Sign in',
    actionText: 'Login',
    key: 'login',
    fields: [
      {
        label: 'Email',
        placeHolder: 'Email Address',
        error: 'Please enter proper email address.',
        key: 'email',
        type: 'email',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Email,
      },
      {
        label: 'Password',
        placeHolder: 'Your password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'password',
        type: 'password',
        otp: 'otp',
        secure: true,
        icon: Assets.Images.icons.Lock,
      },
    ],
    bottomActions: [
      {
        title: 'Don’t have an account?',
        action: 'Sign up',
        key: 'signup',
      },
    ],
  },
  LEAGUE_SIGN: {
    title: 'Sign in',
    actionText: 'Sign in',
    key: 'login',
    spacing: 'tight',
    fields: [
      {
        label: 'Email',
        placeHolder: 'Email Address',
        error: 'Please enter proper email address.',
        key: 'email',
        type: 'email',
        secure: false,
        otp: 'otp',
        icon: Assets.Images.icons.Mail,
      },
      {
        label: 'Password',
        placeHolder: 'Your password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'password',
        type: 'password',
        otp: 'otp',
        secure: true,
        icon: Assets.Images.icons.Lock,
      },
    ],
    bottomActions: [],
  },
  SIGNUP: {
    title: 'Sign up',
    actionText: 'Sign up',
    key: 'signup',
    fields: [
      {
        label: 'Full Name',
        placeHolder: 'Full Name',
        error: 'Please provide your your full name.',
        key: 'name',
        type: 'string',
        secure: false,
        otp: 'otp',
        icon: Assets.Images.icons.User,
      },
      {
        label: 'Email Address',
        placeHolder: 'Email Address',
        error: 'Please enter proper email address.',
        key: 'email',
        type: 'email',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Email,
      },
      {
        label: 'Business Name',
        placeHolder: 'Business Name',
        error: 'Please enter proper business name.',
        key: 'email',
        type: 'email',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Business,
      },
      {
        label: 'Phone Number',
        placeHolder: 'Phone Number',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'phone',
        type: 'phone',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Smartphone,
      },
      {
        label: 'Password',
        placeHolder: 'Your password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'password',
        type: 'password',
        otp: 'otp',
        secure: true,
        icon: Assets.Images.icons.Lock,
      },
      {
        label: 'Confirm Password',
        placeHolder: 'Confirm password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'cpassword',
        type: 'password',
        otp: 'otp',
        secure: true,
        icon: Assets.Images.icons.Lock,
      },
    ],
    bottomActions: [
      {
        title: 'Already have an account?',
        action: 'Sign in',
        key: 'signin',
      },
    ],
  },
  FORGET_PASS: {
    title: 'Forgot Password',
    actionText: 'Reset',
    key: 'forget_pass',
    fields: [
      {
        label: 'Email Address',
        placeHolder: 'jhonsmith@gmail.com',
        error: 'Please enter proper email address.',
        key: 'email',
        type: 'email',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.LoginMail,
      },
    ],
  },
  VERIFY_CODE: {
    title: 'Forgot Password',
    actionText: 'Verify',
    key: 'code',
    fields: [
      {
        label: 'Email Address',
        placeHolder: 'jhonsmith@gmail.com',
        error: 'Please enter proper email address.',
        key: 'code',
        type: 'otp',
        secure: false,
        otp: 'otp',
        icon: Assets.Images.icons.LoginMail,
      },
    ],
  },
  RESET_PASSWORD: {
    title: 'Reset Password',
    actionText: 'Reset Password',
    key: 'code',
    fields: [
      {
        label: 'Password',
        placeHolder: 'Your password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'password',
        type: 'password',
        secure: true,
        otp: 'otp',
        icon: Assets.Images.icons.Lock,
      },
      {
        label: 'Confirm Password',
        placeHolder: 'Confirm password',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'cpassword',
        type: 'password',
        otp: 'otp',
        secure: true,
        icon: Assets.Images.icons.Lock,
      },
    ],
    bottomActions: [
      {
        title: 'Don’t have an account?',
        action: 'Sign up',
        key: 'signup',
      },
    ],
  },
  EDIT_PROFILE: {
    title: '',
    actionText: 'Submit For Validation',
    key: 'code',
    fields: [
      {
        label: 'Full Name',
        placeHolder: 'Full Name',
        error: 'Please provide your your full name.',
        key: 'name',
        type: 'bg',
        secure: false,
        otp: 'otp',
        icon: Assets.Images.icons.User,
      },
      {
        label: 'Email Address',
        placeHolder: 'jhonsmith@gmail.com',
        error: 'Please enter proper email address.',
        key: 'code',
        type: 'bg',
        secure: false,
        otp: 'otp',
        icon: Assets.Images.icons.LoginMail,
      },
      {
        label: 'Business Name',
        placeHolder: 'Business Name',
        error: 'Please enter proper business name.',
        key: 'email',
        type: 'bg',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Business,
      },
      {
        label: 'Phone Number',
        placeHolder: 'Phone Number',
        error: 'Password must be atleast 8 characters long, including uppercase and number.',
        key: 'phone',
        type: 'bg',
        otp: 'otp',
        secure: false,
        icon: Assets.Images.icons.Smartphone,
      },
    ],
    bottomActions: [],
  },
  ADD_NEWEVENT: {
    title: '',
    actionText: 'Submit For Validation',
    key: 'code',
    fields: [
      {
        label: 'Title',
        placeHolder: 'Title',
        error: 'Please provide your your full name.',
        key: 'title',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Subtitle/Tagline',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'subtitle',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Property',
        label2: 'Property 2',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'property',
        type: 'dropdown',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Time',
        placeHolder: 'Time',
        error: 'Please provide your your full name.',
        key: 'time',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Public/Private',
        label2: 'Lorem',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'public',
        type: 'dropdown',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Event Categories',
        label2: 'Lorem',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'event',
        type: 'dropdown',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Description',
        placeHolder: 'Description',
        error: 'Please provide your your full name.',
        key: 'description',
        type: 'textbox',
        secure: false,
        otp: 'otp',
      },
    ],
    bottomActions: [],
  },
  ADD_NEWPROPERTY: {
    title: '',
    actionText: 'Submit For Validation',
    key: 'code',
    fields: [
      {
        label: 'Name',
        placeHolder: 'Name',
        error: 'Please provide your your full name.',
        key: 'name',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Location',
        placeHolder: 'Location',
        error: 'Please provide your your full name.',
        key: 'location',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Address',
        placeHolder: 'Address',
        error: 'Please provide your your full name.',
        key: 'address',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Description',
        placeHolder: 'Description',
        error: 'Please provide your your full name.',
        key: 'description',
        type: 'textbox',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Capacity',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'capacity',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
    ],
    bottomActions: [],
  },
  EDIT_PROPERTY: {
    title: '',
    actionText: 'Submit For Validation',
    key: 'code',
    fields: [
      {
        label: 'Name',
        placeHolder: 'Name',
        error: 'Please provide your your full name.',
        key: 'name',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Location',
        placeHolder: 'Location',
        error: 'Please provide your your full name.',
        key: 'location',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Address',
        placeHolder: 'Address',
        error: 'Please provide your your full name.',
        key: 'address',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Description',
        placeHolder: 'Description',
        error: 'Please provide your your full name.',
        key: 'description',
        type: 'textbox',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Capacity',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'capacity',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
    ],
    bottomActions: [],
  },
  EDIT_EVENT: {
    title: '',
    actionText: 'Submit For Validation',
    key: 'code',
    fields: [
      {
        label: 'Title',
        placeHolder: 'Title',
        error: 'Please provide your your full name.',
        key: 'title',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Subtitle/Tagline',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'subtitle',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Property',
        label2: 'Property 2',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'property',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Time',
        placeHolder: 'Time',
        error: 'Please provide your your full name.',
        key: 'time',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Public/Private',
        label2: 'Lorem',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'public',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Event Categories',
        label2: 'Lorem',
        placeHolder: 'Subtitle/Tagline',
        error: 'Please provide your your full name.',
        key: 'event',
        type: 'bg',
        secure: false,
        otp: 'otp',
      },
      {
        label: 'Description',
        placeHolder: 'Description',
        error: 'Please provide your your full name.',
        key: 'description',
        type: 'textbox',
        secure: false,
        otp: 'otp',
      },
    ],
    bottomActions: [],
  },
}
